drop table BangOverAdverts, BangOverLists, Celebrities, CelebrityRequests;

create table BangOverAdverts (Indext bigint IDENTITY(0,1) PRIMARY KEY, Name varchar(50) not null, Picture varchar(50) not null, Link varchar(50) not null );

create table BangOverLists (Indext bigint IDENTITY(0,1) PRIMARY KEY, UserIndex bigint not null, OrderRank bigint not null, CelebrityIndex bigint not null, UpLock bit not null default 0, DownLock bit not null default 0);

create table Celebrities (Indext bigint IDENTITY(0,1) PRIMARY KEY, Name varchar(50) not null, Sex varchar(1) not null, Picture varchar(50) not null, UploadUserIndex bigint not null );

create table CelebrityRequests (Indext bigint IDENTITY(0,1) PRIMARY KEY, Name varchar(50) not null, Sex varchar(1) not null, Picture varchar(50) not null, UploadUserIndex bigint not null );

insert into BangOverAdverts (Name, Picture, Link) VALUES ('Roosterteeth 1', 'RoosterTeeth1.png', 'http://www.RoosterTeeth.com');
insert into BangOverAdverts (Name, Picture, Link) VALUES ('Roosterteeth 2', 'RoosterTeeth2.jpg', 'http://www.RoosterTeeth.com');
insert into BangOverAdverts (Name, Picture, Link) VALUES ('Roosterteeth 3', 'RoosterTeeth3.jpg', 'http://www.RoosterTeeth.com');
insert into BangOverAdverts (Name, Picture, Link) VALUES ('Roosterteeth 4', 'RoosterTeeth4.jpg', 'http://www.RoosterTeeth.com');
insert into BangOverAdverts (Name, Picture, Link) VALUES ('Roosterteeth 5', 'RoosterTeeth5.jpg', 'http://www.RoosterTeeth.com');
insert into BangOverAdverts (Name, Picture, Link) VALUES ('Roosterteeth 6', 'RoosterTeeth6.jpg', 'http://www.RoosterTeeth.com');

insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Natalie Portman',			'F', 'NataliePortman.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Rachel Leigh Cook',			'F', 'RachelLeighCook.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Keira Knightley',			'F', 'KeiraKnightley.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Maria Thayer',				'F', 'MariaThayer.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Alicia Witt',				'F', 'AliciaWitt.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Alexi Bledel',				'F', 'AlexisBledel.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ali Larter',					'F', 'AliLarter.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Alicia Keys',				'F', 'AliciaKeys.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Alicia Silverstone',			'F', 'AliciaSilverstone.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Alyssa Milano',				'F', 'AlyssaMilano.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Amy Adams',					'F', 'AmyAdams.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('April Bowlby',				'F', 'AprilBowlby.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bailey Jay',					'W', 'BaileyJay.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Barbara Dunkelman',			'F', 'BarbaraDunkelman.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Beyonce Knowles',			'F', 'BeyonceKnowles.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bianca Kajlich',				'F', 'BiancaKajlich.jpeg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bonnie Wright',				'F', 'BonnieWright.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bree Turner',				'F', 'BreeTurner.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bridgit Mendler',			'F', 'BridgitMendler.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bryce Dallas Howard',		'F', 'BryceDallasHoward.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Christina Hendricks',		'F', 'ChristinaHendricks.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Deborah Ann Woll',			'F', 'DeborahAnnWoll.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Elise Williams',				'F', 'EliseWilliams.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Elizabeth Banks',			'F', 'ElizabethBanks.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Elizabeth Olsen',			'F', 'ElizabethOlsen.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Elizabeth Tulloch',			'F', 'ElizabethTulloch.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ellie Kemper',				'F', 'EllieKemper.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Emma Stone',					'F', 'EmmaStone.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Emma Watson',				'F', 'EmmaWatson.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Erica Cerra',				'F', 'EricaCerra.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Erin Way',					'F', 'ErinWay.jpg',						0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Evan Rachel Wood',			'F', 'EvanRachelWood.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Evanna Lynch',				'F', 'EvannaLynch.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Felicia Day',				'F', 'FeliciaDay.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Gillian Jacobs',				'F', 'GillianJacobs.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ian Harvie',					'T', 'IanHarvie.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jacqueline Emerson',			'F', 'JacquelineEmerson.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jamie Clayton',				'W', 'JamieClayton.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jena Malone',				'F', 'JenaMalone.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jessica Chastain',			'F', 'JessicaChastain.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Joanne Kelly',				'F', 'JoanneKelly.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Katee Sackhoff',				'F', 'KateeSackhoff.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Kelly Stables',				'F', 'KellyStables.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Kristen Bell',				'F', 'KristenBell.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Kristen Wig',				'F', 'KristenWig.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Rose Leslie',				'F', 'RoseLeslie.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Sarah Gadon',				'F', 'SarahGadon.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Selma Blair',				'F', 'SelmaBlair.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Sophie Turner',				'F', 'SophieTurner.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Spencer Grammer',			'F', 'SpencerGrammer.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Taylor Swift',				'F', 'TaylorSwift.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Chris Hemsworth',			'M', 'ChrisHemsworth.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Colin Farrell',				'M', 'ColinFarrell.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ryan Reynolds',				'M', 'RyanReynolds.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Megan West',					'F', 'MeganWest.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Andreas Krieger',			'T', 'AndreasKrieger.png',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Balian Buschbaum',			'T', 'BalianBuschbaum.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Buck Angel',					'T', 'BuckAngel.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Chaz Bono',					'T', 'ChazBono.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Loren Cameron',				'T', 'LorenCameron.png',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Lucas Silveira',				'T', 'LucasSilveira.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ryan Sallens',				'T', 'RyanSallens.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Thomas Beatie',				'T', 'ThomasBeatie.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Sofia Vergara',				'F', 'SofiaVergara.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jacqueline Toboni',			'F', 'JacquelineToboni.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jaime Ray Newman',			'F', 'JaimeRayNewman.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ariel Winter',				'F', 'ArielWinter.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bella Thorne',				'F', 'BellaThorne.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Claire Coffee',				'F', 'ClaireCoffee.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Dakota Fanning',				'F', 'DakotaFanning.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Daniela Bobadilla',			'F', 'DanielaBobadilla.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Eden Sher',					'F', 'EdenSher.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Galadriel Stineman',			'F', 'GaladrielStineman.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Gia Mantegna',				'F', 'GiaMantegna.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ginny Gardner',				'F', 'GinnyGardner.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Greer Grammer',				'F', 'GreerGrammer.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Judy Greer',					'F', 'JudyGreer.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Julie Bowman',				'F', 'JulieBowen.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Kathleen Rose Perkins',		'F', 'KathleenRosePerkins.jpeg',		0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Mila Kunis',					'F', 'MilaKunis.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Molly Quinn',				'F', 'MollyQuinn.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Morena Baccarin',			'F', 'MorenaBaccarin.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Sarah Hyland',				'F', 'SarahHyland.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Karen Gillan',				'F', 'KarenGillan.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Amy Smart',					'F', 'AmySmart.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Amber Rayne',				'F', 'AmberRayne.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('August Ames',				'F', 'AugustAmes.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Aurora Snow',				'F', 'AuroraSnow.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Charlotte Stokely',			'F', 'CharlotteStokely.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Emmy Rossum',				'F', 'EmmyRossum.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Gauge',						'F', 'Gauge.jpg',						0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Isis Love',					'F', 'IsisLove.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jasmine Lynn',				'F', 'JasmineLynn.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jenna Haze',					'F', 'JennaHaze.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Madison Young',				'F', 'MadisonYoung.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Alexis Arquette',			'W', 'AlexisArquette.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Anna Sophia Robb',			'F', 'AnnaSophiaRobb.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Catlyn Jenner',				'W', 'CatlynJenner.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Caity Lotz',					'F', 'CaityLotz.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Candice Patton',				'F', 'CandicePatton.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Candis Cayne',				'W', 'CandisCayne.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Carlos Valdea',				'M', 'CarlosValdea.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Carmen Carrera',				'W', 'CarmenCarrera.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Cassie Brooks',				'W', 'CassieBrooks.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Charlie Somik Chan',			'W', 'CharlieSomikChan.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Daisy Ridley',				'F', 'DaisyRidley.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Danielle Panabaker',			'F', 'DaniellePanabaker.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Dominic Purcell',			'M', 'DominicPurcell.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Domino Presley',				'W', 'DominoPresley.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Dwayne Johnson',				'M', 'DwayneJohnson.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Edyn Blair',					'W', 'EdynBlair.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Ellery Sweet',				'W', 'EllerySweet.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Emily Bett Rickards',		'F', 'EmilyBettRickards.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Emily Kinney',				'F', 'EmilyKinney.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Erika Ervin',				'W', 'ErikaErvin.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Fate Model',					'F', 'FateModel.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Grant Gustin',				'M', 'GrantGustin.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Hazel Tucker',				'W', 'HazelTucker.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Isis King',					'W', 'IsisKing.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jane Marie',					'W', 'JaneMarie.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jesse L Martin',				'M', 'JesseLMartin.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jessica Camacho',			'F', 'JessicaCamacho.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Katherine McNamara',			'F', 'KatherineMcNamara.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Katie Cassidy',				'F', 'KatieCassidy.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Keiynan Lonsdale',			'M', 'KeiynanLonsdale.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Kelly Klamour',				'W', 'KellyKlaymour.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Kitti Kaiti',				'W', 'KittiKaiti.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Laverne Cox',				'W', 'LaverneCox.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Leighton Meester',			'F', 'LeightonMeester.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Bianca Freire',				'W', 'BiancaFreire.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Lily Wachowski',				'W', 'LilyWachowski.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Lizzy Caplan',				'F', 'LizzyCaplan.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Mandy Mitchell',				'W', 'MandyMitchell.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Mark Hamil',					'M', 'MarkHamil.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Matt Letscher',				'M', 'MattLetscher.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Melissa Benoist',			'F', 'MelissaBenoist.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Shantel Van Santen',			'F', 'ShantelVanSanten.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Stephen Amell',				'M', 'StephenAmell.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Susan Coffey',				'F', 'SusanCoffey.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Teddy Sears',				'M', 'TeddySears.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Tom Cavanagh',				'M', 'TomCavanagh.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Tom Felton',					'M', 'TomFelton.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Trace Lisette',				'W', 'TraceLisette.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Violet Beane',				'F', 'VioletBeane.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Whitney Cummings',			'F', 'WhitneyCummings.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Willa Holland',				'F', 'WillaHolland.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Zoe Lister Jones',			'F', 'ZoeListerJones.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Amanda Seyfried',			'F', 'AmandaSeyfried.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Arthur Darvil',				'M', 'ArthurDarvil.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Brandon Routh',				'M', 'BrandonRouth.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Calista Rockhart',			'F', 'CalistaRockhart.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Chris Wood',					'M', 'ChrisWood.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Chyler Leigh',				'F', 'ChylerLeigh.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Colton Haynes',				'M', 'ColtonHaynes.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('David Harewood',				'M', 'DavidHarewood.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('David Ramsey',				'M', 'DavidRamsey.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Echo Kellum',				'M', 'EchoKellum.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Elizabeth J Carlisle',		'F', 'ElizabethJCarlisle.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Eugene Boyd',				'M', 'EugeneBoyd.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Floriana Lima',				'F', 'FlorianaLima.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Franz Drameh',				'M', 'FranzDrameh.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Italia Ricci',				'F', 'ItaliaRicci.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jeffrey Dean Morgan',		'M', 'JeffreyDeanMorgan.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jensen Ackles',				'M', 'JensenAckles.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jeremy Jordan',				'M', 'JeremyJordan.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jessica De Gouw',			'F', 'JessicaDeGouw.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Jewel Staite',				'F', 'JewelStaite.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Joe Dinicol',				'M', 'JoeDinicol.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('John Barrowman',				'M', 'JohnBarrowman.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Katie McGrath',				'F', 'KatieMcGrath.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Madison McLaughlin',			'F', 'MadisonMcLaughlin.jpg',			0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Maisie Richardson Sellers',	'F', 'MaisieRichardson Sellers.jpg',	0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Manu Bennett',				'M', 'ManuBennett.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Mehcad Brooks',				'M', 'MehcadBrooks.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Michael Rowe',				'M', 'MichaelRowe.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Nathan Fillon',				'M', 'NathanFillon.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Neal McDonough',				'M', 'NealMcDonough.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Nick Zano',					'M', 'NickZano.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Paul Blackthorne',			'M', 'PaulBlackthorne.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Peter Facinelli',			'M', 'PeterFacinelli.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Rick Gonzalez',				'M', 'RickGonzalez.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Summer Glau',				'F', 'SummerGlau.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Tamzin Merchant',			'F', 'TamzinMerchant.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Teri Hatcher',				'F', 'TeriHatcher.jpg',					0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Veronica Belmont',			'F', 'VeronicaBelmont.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Wentworth Miller',			'M', 'WentworthMiller.jpg',				0);
insert into Celebrities (Name, Sex, Picture, UploadUserIndex) VALUES ('Wil Wheaton',				'M', 'WilWheaton.jpg',					0);
